version: "3.8"
services:
  frontend:
    image: frontend:marka
    ports:
      - 80:80
    depends_on:
      - gateway
    environment:
      REACT_APP_API_URL: "http://localhost:4000/api"
  gateway:
    image: apigateway:marka
    ports:
      - 4000:4000
    depends_on:
      - auth
    environment:
      SERVICE: "API GATEWAY"
      PORT: "4000"
      HOSTNAME: "http://gateway:4000"
    env_file:
      - ./docker.env
  auth:
    image: authservice:marka
    ports:
      - 4001:4001
    depends_on:
      - mongo
    environment:
      SERVICE: "AUTH SERVICE"
      PORT: "4001"
      HOSTNAME: "http://auth:4001"
    env_file:
      - ./docker.env
      - ./docker-mongo.env
      - ./docker-transporter.env
  user:
    image: userservice:marka
    ports:
      - 4002:4002
    depends_on:
      - mongo
    environment:
      SERVICE: "USER SERVICE"
      PORT: "4002"
      HOSTNAME: "http://user:4002"
    env_file:
      - ./docker.env
      - ./docker-mongo.env
      - ./docker-transporter.env
  code:
    image: codeservice:marka
    ports:
      - 4004:4004
    depends_on:
      - mongo
    environment:
      SERVICE: "CODE SERVICE"
      PORT: "4004"
      HOSTNAME: "http://code:4004"
    env_file:
      - ./docker.env
      - ./docker-mongo.env
  transaction:
    image: transactionservice:marka
    ports:
      - 4006:4006
    depends_on:
      - mongo
    environment:
      SERVICE: "TRANSACTION SERVICE"
      PORT: "4006"
      HOSTNAME: "http://transaction:4006"
    env_file:
      - ./docker.env
      - ./docker-mongo.env
  qr:
    image: qrservice:marka
    ports:
      - 4008:4008
    depends_on:
      - mongo
    environment:
      SERVICE: "QR SERVICE"
      PORT: "4008"
      HOSTNAME: "http://qr:4008"
    env_file:
      - ./docker.env
  mongo:
    image: mongo
    ports:
      - "27017:27017"
