openapi: 3.0.1
info:
  title: Marka - Transaction Service
  description: Api documentation of Transaction Service
  version: 1.0.0
externalDocs:
  description: Find out more about Marka
  url: https://marka.club/docs
servers:
  - url: https://localhost:8080
tags:
  - name: Transactions
paths:
  /transaction:
    post:
      tags:
        - Operations
      operationId: createTransaction
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
      responses:
        200:
          description: OK
components:
  schemas:
    Transaction:
      type: object
      properties:
        id:
          type: integer
          format: int64
        date:
          type: string
          format: date-time
        storeId:
          type: integer
          format: int64
        customerId:
          type: integer
          format: int64
        type:
          type: string
          enum: [PAID, FREE]
        qrId:
          type: integer
          format: int64
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    Error:
      description: Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    UnauthorizedError:
      description: Access token is missing or invalid
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: Not found!
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
